const { GoogleSpreadsheet } = require('google-spreadsheet');
require('dotenv').config()
// Initialize the sheet - doc ID is the long id in the sheets URL
const doc = new GoogleSpreadsheet('1Mv6rkHzpzYsvJxoVFO9rh7xNvlXYGBlkR5g1sB3P9QY');
// console.log(process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL)
console.log(process.env.GOOGLE_PRIVATE_KEY)


const authGoogle = async function start() {
await doc.useServiceAccountAuth({
    // env var values are copied from service account credentials generated by google
    // see "Authentication" section in docs for more info
    client_email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
    private_key: process.env.GOOGLE_PRIVATE_KEY.replace(/\\n/g, "\n"),
  });
}

authGoogle();

const loadGoogleInfo = async function() {
await doc.loadInfo(); // loads document properties and worksheets
console.log(doc.title);
const sheet = doc.sheetsByIndex[0];
sheet.addRow(["lala","lala","lala"]);
}

loadGoogleInfo();